INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Banana 123', 'Fruta 1', 'Banana', 1);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Limão 444', 'Fruta 2', 'Limão', 2);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Uva 445', 'Fruta 3', 'Uva', 3);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Pêssego 654', 'Fruta 4', 'Pêssego', 4);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Tamarindo 987', 'Fruta 5', 'Tamarindo', 5);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES (' 098', 'Fruta 6', 'Kiwi', 6);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Laranja 101', 'Fruta 7', 'Laranja', 7);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Tomate 665', 'Fruta 8', 'Tomate', 8);
INSERT INTO exercicio10.item_ (descricao, detalhes, nome, id) VALUES ('Morango 572', 'Fruta 9', 'Morango', 9);